---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-analytics-chatbot-pvc
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prod-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-03a4802c295a7e378

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-analytics-chatbot-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: prod-efs-sc
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: chatbot
    meta.helm.sh/release-namespace: default
  labels:
    team: chatbot
  name: prod-chatbot-srv
  namespace: default
spec:
  minReadySeconds: 4
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prod-chatbot-srv
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "50000"
        prometheus.io/scrape: "true"
        vault.security.banzaicloud.io/vault-addr: http://vault:8200
        vault.security.banzaicloud.io/vault-namespace: vault-infra
        vault.security.banzaicloud.io/vault-path: kubernetes
        vault.security.banzaicloud.io/vault-role: prod-chatbot
        vault.security.banzaicloud.io/vault-serviceaccount: default
        vault.security.banzaicloud.io/vault-skip-verify: "true"
      creationTimestamp: null
      labels:
        app: prod-chatbot-srv
    spec:
      containers:
        image: 845742683201.dkr.ecr.ap-south-1.amazonaws.com/chatbot-prod:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 200
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 4
        name: prod-chatbot-srv
        ports:
        - containerPort: 3000
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 4
        resources:
          limits:
            cpu: "1"
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: efs-analytics-chatbot-pvc
          mountPath: /botpress/data
      volumes:
      - name: efs-analytics-chatbot-pvc
        persistentVolumeClaim:
          claimName: efs-analytics-chatbot-claim
      